//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartDisease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulting
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> C_Patient_age_ { get; set; }
        public string C_Patient_Gender_ { get; set; }
        public string C_Content_ { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
