//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartDisease.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HDEntities : DbContext
    {
        public HDEntities()
            : base("name=HDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consulting> Consultings { get; set; }
        public virtual DbSet<MedicalTopic> MedicalTopics { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Subspecialty> Subspecialties { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<diet_and_food_for_heart_patient> diet_and_food_for_heart_patients { get; set; }
        public virtual DbSet<Heart_disease_and_symptom> Heart_disease_and_symptoms { get; set; }
    }
}
