//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartDisease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heart_disease_and_symptom
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string C_Content_ { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idUser { get; set; }
        public string C_References_ { get; set; }
    
        public virtual User User { get; set; }
    }
}
