//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartDisease.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medical_Topic
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string File { get; set; }
        public string Photo { get; set; }
        public Nullable<decimal> Views { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string UserID { get; set; }
        public Nullable<int> SubspecID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Subspecialty Subspecialty { get; set; }
    }
}
