//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartDisease.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeartEntities : DbContext
    {
        public HeartEntities()
            : base("name=HeartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Consulting> Consultings { get; set; }
        public virtual DbSet<Heart_disease_and_symptom> Heart_disease_and_symptoms { get; set; }
        public virtual DbSet<Medical_Topic> Medical_Topic { get; set; }
        public virtual DbSet<Subspecialty> Subspecialties { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<diet_and_food_for_heart_patient> diet_and_food_for_heart_patients { get; set; }
    }
}
